version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: jupiter_postgres
    restart: always
    environment:
      POSTGRES_USER: jupiter
      POSTGRES_PASSWORD: jupiter123
      POSTGRES_DB: jupiter_chat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
